services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"
  management:
    container_name: management
    build:
      context: .
      dockerfile: ./management-service/Management.Service/Dockerfile
    environment:
      - "RabbitMq__HostName=host.docker.internal"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8001:8080"
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./management-frontend/Dockerfile
    depends_on:
      management:
        condition: service_healthy
    ports:
      - "5173:5173"
